[Interface]
Address = 10.0.0.3/24
PrivateKey = eKK8znhuZEJ5SABB9RQlnPAASzTeWKsqcibbeWOp0Vo=

[Peer]
PublicKey = nGEKLWPQALE/cggiSaTOguy6mMNU7O5HcFd1MlYDQiw=
Endpoint = wireguard-server:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
