[Interface]
Address = 10.0.0.4/24
PrivateKey = ODbAnQdnPEqLks1hH/fp3pltOdovxkTnRJJvgZy0lWc=

[Peer]
PublicKey = nGEKLWPQALE/cggiSaTOguy6mMNU7O5HcFd1MlYDQiw=
Endpoint = 25.44.147.138:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
