[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = KHDu3mDsHTptXQ6211sNOu4qorI+1TQ/p3G0PGU3Nk8=

[Peer]
PublicKey = oNBZlvDR+9Y2coZ0OOLmMgq5MnXF6XeOXA6eNXxQjzs=
AllowedIPs = 10.0.0.2/32

[Peer]
PublicKey = ypibUEuLzIZ70IId4c8JEfCydvPD67bdz9If0Z+x8CU=
AllowedIPs = 10.0.0.3/32

[Peer]
PublicKey = PJzjBUN6l2oq2mu95qqFnLIyPByltaGVUarAvWGVmGM=
AllowedIPs = 10.0.0.4/32
