[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = qDeOWqp+EI4ax3KDm7/m6TtqaAZSnXkW4TbStK1Vcn4=

[Peer]
PublicKey = GPvGYMPDVLWRezz108Q1T8JoFX4MxEcGXI38l8UW5n0=
AllowedIPs = 10.0.0.2/32

[Peer]
PublicKey = ypibUEuLzIZ70IId4c8JEfCydvPD67bdz9If0Z+x8CU=
AllowedIPs = 10.0.0.3/32

[Peer]
PublicKey = PJzjBUN6l2oq2mu95qqFnLIyPByltaGVUarAvWGVmGM=
AllowedIPs = 10.0.0.4/32
